import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-truckload-freight-fuel-surcharge-audit",
  "engine": "recovery",
  "title": "Truckload Freight & Fuel Surcharge Audit",
  "shortTitle": "Truckload Freight and Fuel Surcharge Audit",
  "tagline": "Quantify, recover, and prevent financial leakage through truckload freight & fuel surcharge audit",
  "industry": "Truckload Spend Recovery",
  "uiPort": 4606,
  "apiPort": 5606,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Truckload Freight & Fuel Surcharge Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Carrier Billed Amount",
    "expectedLabel": "Contract-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Truckload Freight & Fuel Surcharge Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("carrier-broker-agreement-library","TFF01","Carrier broker agreement library","Execute carrier broker agreement library using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed carrier broker agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Carrier broker agreement library Reference","text","TFF01-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("lane-rate-registry","TFF02","Lane rate registry","Execute lane rate registry using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed lane rate registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Lane rate registry Reference","text","TFF02-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("tender-load-ingestion","TFF03","Tender load ingestion","Execute tender load ingestion using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed tender load ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Tender load ingestion Reference","text","TFF03-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("contract-versus-spot-determination","TFF04","Contract versus spot determination","Execute contract versus spot determination using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed contract versus spot determination decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Contract versus spot determination Reference","text","TFF04-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("linehaul-recalculation","TFF05","Linehaul recalculation","Execute linehaul recalculation using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed linehaul recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Linehaul recalculation Reference","text","TFF05-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("fuel-index-validation","TFF06","Fuel index validation","Execute fuel index validation using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed fuel index validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Fuel index validation Reference","text","TFF06-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("mileage-calculation","TFF07","Mileage calculation","Execute mileage calculation using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed mileage calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Mileage calculation Reference","text","TFF07-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("stop-off-charge-audit","TFF08","Stop-off charge audit","Execute stop-off charge audit using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed stop-off charge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Stop-off charge audit Reference","text","TFF08-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("layover-validation","TFF09","Layover validation","Execute layover validation using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed layover validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Layover validation Reference","text","TFF09-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("detention-validation","TFF10","Detention validation","Execute detention validation using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed detention validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Detention validation Reference","text","TFF10-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("lumper-evidence","TFF11","Lumper evidence","Execute lumper evidence using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed lumper evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Lumper evidence Reference","text","TFF11-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("tonu-validation","TFF12","TONU validation","Execute tonu validation using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed tonu validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","TONU validation Reference","text","TFF12-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("invoice-matching","TFF13","Invoice matching","Execute invoice matching using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed invoice matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Invoice matching Reference","text","TFF13-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("carrier-dispute-workflow","TFF14","Carrier dispute workflow","Execute carrier dispute workflow using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed carrier dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Carrier dispute workflow Reference","text","TFF14-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]}),
feature("lane-carrier-analytics","TFF15","Lane carrier analytics","Execute lane carrier analytics using carrier and broker agreements, lane rates, tenders, loads, mileage, fuel indexes, stops, detention, layovers, lumpers, TONU events, invoices, and credits.","Produce a governed lane carrier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Load","text","Carrier / Load · Standard Case"],["caseReference","Lane carrier analytics Reference","text","TFF15-2026-001"],["billedAmount","Carrier Billed Amount","currency",697500],["supportedAmount","Contract-Supported Amount","currency",599850],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Carrier broker agreement library case","Lane rate registry case","Tender load ingestion case","Contract versus spot determination case","Linehaul recalculation case"]})
]);
